package ru.gb.common;

public enum CommandType {

    DOWNLOAD, LOGIN, UPLOAD, READY_TO_UPLOAD, UPLOAD_FINISHED, FILESLIST, READY_TO_DOWNLOAD,
    READY_TO_RECIEVE, FINISHED_DOWNLOAD, LOGIN_OK, CLOUD_FILESLIST, REGISTRATION_FAILED

}
